# -*- coding: utf-8 -*-
"""Assistente_simples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCf43If_DuRQ5tgSYcqfhW0zFn374ev8
"""

from openai import OpenAI


client = OpenAI(api_key='')
def gerar_resposta(contexto, pergunta):
    """
    Gera uma resposta para uma pergunta com base em um contexto fornecido.

    Args:
        contexto (str): O contexto ou informação de fundo.
        pergunta (str): A pergunta a ser respondida.

    Returns:
        str: A resposta gerada pela IA.
    """

    prompt = f"{contexto}\n\nPergunta: {pergunta}\nResposta:"


    resposta = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "Você é um assistente útil."},
            {"role": "user", "content": prompt}
        ]
    )


    return resposta.choices[0].message.content


def main():
    print("Bem-vindo ao Assistente de IA! Digite 'sair' a qualquer momento para encerrar.")


    contexto = "A OpenAI é uma empresa de pesquisa em inteligência artificial."
    print(f"Contexto atual: {contexto}\n")

    while True:

        pergunta = input("Você: ")

        if pergunta.lower() == "sair":
            print("Encerrando o programa. Até mais!")
            break


        resposta = gerar_resposta(contexto, pergunta)
        print(f"\nAssistente: {resposta}\n")


if __name__ == "__main__":
    main()